// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/interfaces/repository.go
//
// Generated by this command:
//
//	mockgen -source ./internal/interfaces/repository.go -package testutil -destination ./internal/interfaces/testutil/repository_mock.go
//

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIContractRepository is a mock of IContractRepository interface.
type MockIContractRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContractRepositoryMockRecorder
	isgomock struct{}
}

// MockIContractRepositoryMockRecorder is the mock recorder for MockIContractRepository.
type MockIContractRepositoryMockRecorder struct {
	mock *MockIContractRepository
}

// NewMockIContractRepository creates a new mock instance.
func NewMockIContractRepository(ctrl *gomock.Controller) *MockIContractRepository {
	mock := &MockIContractRepository{ctrl: ctrl}
	mock.recorder = &MockIContractRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractRepository) EXPECT() *MockIContractRepositoryMockRecorder {
	return m.recorder
}

// GetContractRawModule mocks base method.
func (m *MockIContractRepository) GetContractRawModule(contractId string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractRawModule", contractId)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractRawModule indicates an expected call of GetContractRawModule.
func (mr *MockIContractRepositoryMockRecorder) GetContractRawModule(contractId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractRawModule", reflect.TypeOf((*MockIContractRepository)(nil).GetContractRawModule), contractId)
}

// LoadEntity mocks base method.
func (m *MockIContractRepository) LoadEntity(contractId, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadEntity", contractId, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadEntity indicates an expected call of LoadEntity.
func (mr *MockIContractRepositoryMockRecorder) LoadEntity(contractId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadEntity", reflect.TypeOf((*MockIContractRepository)(nil).LoadEntity), contractId, key)
}

// SaveEntity mocks base method.
func (m *MockIContractRepository) SaveEntity(contractId, key string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntity", contractId, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntity indicates an expected call of SaveEntity.
func (mr *MockIContractRepositoryMockRecorder) SaveEntity(contractId, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntity", reflect.TypeOf((*MockIContractRepository)(nil).SaveEntity), contractId, key, data)
}
